### PR TITLE
Make filename Windows-friendly

### PR DESCRIPTION
**Pull request by dkolas**
Rename Path->Bool.swift to PathToBool.swift

I'm trying to build our project on swift in native Windows for the first time, and when the package manager tries to fetch the package, it chokes on this filename.

### CODE REVIEW

**Comment by mxcl** [comment]
Fixed, but I don’t expect this to work on Windows since we expect `/` paths and I don't think anyone has corrected that.

**Comment by dkolas** [comment]
Interesting, thanks! I'll let you know how it goes.

**Comment by mxcl** [comment]
I recently ported this to TypeScript and made it work on Windows, it isn’t too tricky TBH.

**Comment by dkolas** [comment]
Cool, thanks.  Will put up a PR if/when I get there.  Looks like at least one of our other deps doesn't even build on Windows, so having things actually work will be the step after that :)

**Pull request merged**
